### ISSUE TITLE
Fix VS Code Extension build

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#67]
Currently `vsce package` fails with:

```
/home/fsteeg/.nvm/versions/node/v12.14.1/lib/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/fsteeg/.nvm/versions/node/v12.14.1/lib/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
```

Also in the GitHub Action: https://github.com/metafacture/metafacture-fix/runs/4150296248

**Comment by fsteeg** [comment]
Functional review & code review: @fsteeg

**Comment by fsteeg** [comment]
+1
